### PR TITLE
TMC manual: help!

### PR DESCRIPTION
**Pull request by gasche**
I'm preparing a manual chapter on TMC (see #9760). I made the mistake of writing the chapter in one go, without trying to compile, and now I'm plagued by many caml-tex errors that I have the hardest time fixing. Can you help me?

At some point I started creating commits for intermediary states for confusing or hard-to-debug errors. Some errors are sub-optimal because they do not contain line numbers

      Error when parsing the following phrase:
      let[@tail_mod_cons rec bind (f : 'a -> 'a tree) (t : 'a tree) : 'a tree =
      match t with
      | Leaf v -> (f[@tailcall false]) v
      | Node (left, right) -> Node (bind f left, (bind[@tailcall]) f right)

Some errors are horrible because, in addition, they contain no clue as to where the issue may be

      Uncaught exception: Failure("lexing: empty token")
      Fatal error: exception Failure("lexing: empty token")

Finally, some errors are even worse, because they have line numbers (many) but I have *no clue* what it is about those lines that they are talking about:

        Error when evaluating a caml_example environment in extensions/tail_mod_cons.etex, line 176:
        Textual transforms must be well-separated.
        The "underline" transform spanned the interval 113-157,
        intersecting with another "underline" transform  on the 124-138 interval.
        Hind: did you try to elide a code fragment which raised a warning?

Note: one thing that *seems* to be improving the situation with my file has been to replace all occurrences of `"[@tailcall]"` and `"[@tail_mod_cons]"` in TeX context (outside the caml_example environment) by `"[\@tailcall]"` and `"[\@tail_mod_cons]"`. I'm not sure this is necessary or valid, but I suspect that the `@` sign there was somehow getting some other markup machinery very confused (there are occurrences of `@"foo" "bar"@` in other .etex files).

I would be very interested in the following:
- In the short term, help to debug the .etex / fix the markup errors, so that I can submit a documentation PR that builds (it's painful for reviewers to read the .etex directly, I would rather upload a HTML output).
- In the medium term, it would be very nice if you could improve the error-message machinery in caml-tex to provide line numbers on the errors that are missing them. I still have no clue what the last error is about, but I suspect that there might also be something in the parsing code to be made more robust.

P.S.: your `trunk` reference appears to be very old.

### CODE REVIEW

**Comment by Octachron** [comment]
I will have a look, the most worrying part is the question of intersecting underlining; this is supposed to mean that more than one warning is trying to underline the same location, and I don't remember if there is any way to turn off this error right now.

**Comment by gasche** [comment]
Let me first clarify that, by "short term", I certainly did not mean *on a Sunday* (nor: on a holiday tomorrow)!

What you say about the error makes sense; the tail-mod-cons implementation does often have overlapping warnings.

**Comment by Octachron** [comment]
The intersection error should be fixed by ocaml#10746  .
The remaining errors are missing labels  for sections and warning numbers : 
```diff
--- a/manual/src/refman/extensions/tail_mod_cons.etex
+++ b/manual/src/refman/extensions/tail_mod_cons.etex
@@ -203,7 +203,7 @@ let[@tail_mod_cons] rec map_vars f exp =
     Let ((f v, (map_vars[@tailcall]) f def), (map_vars[@tailcall]) f body)
 \end{caml_example*}
 

-\subsection{Danger: getting out of tail-mod-cons}
+\subsection{ss:tmc_danger}{Danger: getting out of tail-mod-cons}
 
 Due to the nature of the tail-mod-cons transformation
 (see Section~\ref{ss:details} for a presentation of transformation):
@@ -254,7 +254,7 @@ The same warning occurs when "append_flatten" is a non-tail-mod-cons
 function of the same recursive group; using the tail-mod-cons
 transformation is a property of individual functions, not whole
 recursive groups.
-\begin{caml_example*}{verbatim}[warning]
+\begin{caml_example*}{verbatim}[warning=71]
 let[@tail_mod_cons] rec flatten = function
 | [] -> []
 | xs :: xss ->
@@ -283,7 +283,7 @@ Non-recursive functions can also be marked "[\@tail_mod_cons]"; this is
 typically useful for local bindings to recursive functions.
 
 Incorrect version:
-\begin{caml_example*}{verbatim}[warning]
+\begin{caml_example*}{verbatim}[warning=51,warning=71]
 let[@tail_mod_cons] rec map_vars f exp =
   let self exp = map_vars f exp in
   match exp with
@@ -308,7 +308,7 @@ parameter (the transformation only works with calls to
 known functions).
 
 For example, consider a substitution function on binary trees:
-\begin{caml_example*}{verbatim}[warning]
+\begin{caml_example*}{verbatim}[warning=72]
 type 'a tree = Leaf of 'a | Node of 'a tree * 'a tree
 
 let[@tail_mod_cons] rec bind (f : 'a -> 'a tree) (t : 'a tree) : 'a tree =
@@ -332,8 +332,7 @@ let[@tail_mod_cons] rec bind (f : 'a -> 'a tree) (t : 'a tree) : 'a tree =
   | Node (left, right) -> Node (bind f left, (bind[@tailcall
```

**Comment by gasche** [comment]
@Octachron I'm revisiting this now. Thanks to your help and location-intersection-support PR, I will have a working manual section and am unblocked. But I still think the error-reporting in other cases should be fixed (it's a UX problem if I need to ask the caml-tex maintainer to understand what's going on); it's not high-priority, but it matters. I propose that we look at this together the next time we met in person and no one has to run urgently.

**Comment by gasche** [comment]
Specifically the following error outputs need fixing:

```
  Error when parsing the following phrase:
  let[@tail_mod_cons rec bind (f : 'a -> 'a tree) (t : 'a tree) : 'a tree =
  match t with
  | Leaf v -> (f[@tailcall false]) v
  | Node (left, right) -> Node (bind f left, (bind[@tailcall]) f right)
```
(missing line numbers)

```
    Unknown caml_example option: [ok].
    Supported options are "ok","error", or "warning=n" (with n a warning number).
```
"ok" should work, and there should be a cue about the multi-warning case because I didn't know about it before your message above.

```
  Uncaught exception: Failure("lexing: empty token")
  Fatal error: exception Failure("lexing: empty token")
```
wat?

**Comment by Octachron** [comment]
I agree that those error messages should be fixed.
We could be definitively do that during a synchronous hacking session.

**Pull request closed without merging**
